[package]
name = "collector"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "OS-specific packet and flow collectors for Local Monitoring"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
serde.workspace = true
tracing.workspace = true
serde_json.workspace = true
thiserror.workspace = true
chrono.workspace = true
parking_lot.workspace = true
tokio.workspace = true
